### ISSUE TITLE
Bad Request Your browser sent a request that this server could not understand

### ISSUE THREAD

**Issue by sant527** [bitnami/bitnami-docker-phppgadmin#5]
I have 

```
  postgresql:
    image: "postgres:13-alpine"
    restart: always
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - postgresql_network

  phppgadmin:
    image: "bitnami/phppgadmin:7.13.0"
    environment:
      DATABASE_HOST: "postgresql"
      DATABASE_SSL_MODE: "disable"
    depends_on:
      - postgresql
    networks:
      - nginx_network
      - postgresql_network
    ports:
      - 80:8080
```

If I am running this on localhost, I can connect to the site. That is `http://localhost` and everything works well

But If I am on server say some ip address: xx.xx.xx.xx and try to connect `http://xx.xx.xx.xx` 

then it says 
```
Bad Request
Your browser sent a request that this server could not understand.
Additionally, a 400 Bad Request error was encountered while trying to use an ErrorDocument to handle the request.
```
